language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - composer selfupdate

install:
  - composer update --prefer-dist

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache